const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test'),path=require('node:path');
const root=path.join(__dirname,'..');
const ctx=vm.createContext({Utilities:{newBlob:text=>({getBytes:()=>Buffer.from(text)})}});
for(const f of ['LegacyCore.gs','Code.gs'])vm.runInContext(fs.readFileSync(path.join(root,'gas',f),'utf8'),ctx);
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const old=read('S2K_F2K_基礎整合檢視器_V4.15.5.js');
const html=read('S2K_F2K_基礎整合檢視器_V4.15.5.html');
const pm=Buffer.from(html.match(/<script[^>]*id="module-source-pm-v100"[^>]*>([\s\S]*?)<\/script>/)[1].trim(),'base64').toString();
const fixture=read('gas/Index.html').match(/const demoText=`([\s\S]*?)`;/)[1];
const pmInput={B:60,H:60,fc:280,fy:4200,Es:2040000,Ab:5.067,cover:6,rebarX:4,rebarY:4,alpha:1.5,forces:[{p:100,mx:10,my:5},{p:300,mx:30,my:20},{p:10000,mx:0,my:0},{p:0,mx:0,my:0},{p:-10000,mx:0,my:0}]};
function plain(x){return JSON.parse(JSON.stringify(x));}
function original(t){const c=vm.createContext({});vm.runInContext(old.slice(old.indexOf('function parseS2K('),old.indexOf('/* ════════ GLOBALS'))+'\n'+old.slice(old.indexOf('const TW_SECTION_CLASSES='),old.indexOf('function twSectionClassTitle')),c);c.model=c.buildModel(c.parseS2K(t));return c;}
function originalLoads(model){const c=vm.createContext({model,zLevels:[...new Set(Object.values(model.joints).map(j=>+j.z.toFixed(3)))].sort((a,b)=>a-b),areaM2Cache:{},loadCalc:{types:[],vals:{},frameSelfWt:true,selfWtMult:(model.loadPats.find(p=>p.selfWtMult>0)||{}).selfWtMult||1},renderLoadCalcUI:()=>{},rebuild:()=>{}});for(const l of model.areaLoads){if(!l.pat)continue;const id='s2k:'+l.pat;(c.loadCalc.vals[l.area]||=( {}))[id]=(c.loadCalc.vals[l.area][id]||0)+l.v;}for(const name of new Set([...model.areaLoads,...model.frameLoads].map(l=>l.pat).filter(Boolean)))c.loadCalc.types.push({id:'s2k:'+name,name});
vm.runInContext(old.slice(old.indexOf('function frameUnitWt('),old.indexOf('function lcDetectSelfWtMult'))+old.slice(old.indexOf('function frameIsHorizontal('),old.indexOf('function lcTypeName'))+old.slice(old.indexOf('function isWeightLoadDirection('),old.indexOf('function lcPreloadS2kLoads'))+old.slice(old.indexOf('function frameLoadResultant('),old.indexOf('function updateLcSelInfo')),c);c.recalcLoadCalc();return c.loadCalc;}
test('demo hand calculations: geometry, area + line load, frame weight',()=>{const r=ctx.analyzeModel({text:fixture,name:'demo'});assert.equal(Object.keys(r.model.joints).length,8);assert.equal(r.model.frames.length,8);assert.equal(r.loads.floors[3]['s2k:DL'],13.2);const wt=Object.values(r.loads.floorFrameDetail).flatMap(Object.values).reduce((s,v)=>s+v.wt,0);assert.ok(Math.abs(wt-32*.008192*7.85)<1e-12);assert.equal(r.sections[0].label,'塑性斷面');});
for(const name of ['工務大樓/工務大樓_20260708_e_model definition.s2k','工務大樓/工務大樓_20260708_f.s2k'])test('real-case legacy parity: '+name,()=>{const text=read(name),o=original(text),r=ctx.analyzeModel({text,name});assert.deepEqual(plain(r.tables),plain(o.parseS2K(text)));assert.deepEqual(plain(r.model),plain(o.model));for(const s of r.sections)assert.deepEqual(plain({...s,name:undefined}),plain(o.twSectionClassify(s.name)));assert.deepEqual(plain(r.loads),plain(originalLoads(o.model)));console.log(JSON.stringify({case:name,bytes:Buffer.byteLength(text),joints:Object.keys(r.model.joints).length,frames:r.model.frames.length,areas:r.model.areas.length,tables:Object.keys(r.tables).length,sections:r.sections.length}));});
test('PM exact parity with embedded old module, including zero and NG cases',()=>{const c=vm.createContext({});vm.runInContext(pm.slice(pm.indexOf('    function calculateRebarCoordinates('),pm.indexOf('    function updateGeomInfo('))+pm.slice(pm.indexOf('    function calculatePMCurve('),pm.indexOf('    function updateResultTable(')),c);const p=pmInput,coords=c.calculateRebarCoordinates(p.B,p.H,p.rebarX,p.rebarY,p.cover),x=c.calculatePMCurve(p.B,p.H,p.fc,p.fy,p.Es,p.Ab,coords,'y',p.cover),y=c.calculatePMCurve(p.H,p.B,p.fc,p.fy,p.Es,p.Ab,coords,'x',p.cover);const r=ctx.calculatePM(p);assert.deepEqual(plain(r.x),plain(x));assert.deepEqual(plain(r.y),plain(y));assert.deepEqual(plain(r.results),plain(c.performBiaxialCheck(p.forces,x.calcPoints,y.calcPoints,p.alpha,x.drawPoints,y.drawPoints)));assert.equal(r.results[0].status,'OK');assert.ok(r.results[2].status.startsWith('NG'));console.log('PM reference',JSON.stringify(r.results));});
test('classification boundary and missing dimensions',()=>{const m={sections:{H:{shape:'I',mat:'S',t3:.4,t2:.28,tf:.01,tw:.02}},materials:{S:{fy:10000}}};assert.equal(ctx.legacyClassification_(m,'H').items[0].rank,0);m.sections.H.t2+=1e-6;assert.equal(ctx.legacyClassification_(m,'H').items[0].rank,1);const r=ctx.analyzeModel({text:fixture.replace(' t3=0.4','')});assert.equal(r.sections[0].applicable,false);});
test('v9 fallback, continued records, CRLF, repeated tables, quoted SAFE keys',()=>{const t='TABLE: "JOINT COORDINATES"\r\nJoint=1 XorR=0 _\r\n Y=1 Z=2\r\nTABLE: "JOINT COORDINATES"\r\nJoint=2 XorR=3 Y=1 Z=2';assert.equal(ctx.analyzeModel({text:t}).model.joints['1'].z,2);const r=ctx.analyzeModel({text:fixture.replace(/TABLE: "LOAD PATTERN DEFINITIONS"\n[^\n]*\n/,'').replace('MATERIAL PROPERTIES 03A - STEEL DATA','MATERIAL PROPERTIES 03 - DESIGN STEEL').replaceAll('LoadPat=','LoadCase=')});assert.ok(r.model.loadPats.some(x=>x.name==='DL'));const parsed=ctx.parseTables_('TABLE: "F"\n"Unique Name"="F1" "Section Property"="A B"');assert.equal(parsed.F[0]['Section Property'],'A B');});
test('SAFE geometry fields from legacy F2K exporter',()=>{const t='TABLE: "PROGRAM CONTROL"\nProgramName=SAFE CurrUnits="Tonf, m, C"\nTABLE: "POINT OBJECT CONNECTIVITY"\nUniqueName=1 X=0 Y=0 Z=0\nUniqueName=2 X=1 Y=0 Z=0\nUniqueName=3 X=1 Y=1 Z=0\nTABLE: "FLOOR OBJECT CONNECTIVITY"\n"Unique Name"=F1 UniquePt1=1 UniquePt2=2 UniquePt3=3';const r=ctx.analyzeModel({text:t});assert.equal(r.format,'SAFE F2K');assert.equal(r.model.areas[0].joints.length,3);assert.equal(r.loads,null);});
test('reject malformed, missing references, LFS, prototype keys; units fail closed',()=>{for(const t of ['','not a model','version https://git-lfs.github.com/spec/v1','TABLE: "__proto__"\nA=B','TABLE: "X"\nJoint=__proto__','TABLE: "JOINT COORDINATES"\nJoint=1 GlobalX=no GlobalY=0 GlobalZ=0',fixture.replace('JointI=1 JointJ=5','JointI=999 JointJ=5')])assert.throws(()=>ctx.analyzeModel({text:t}));assert.equal(ctx.analyzeModel({text:fixture.replace('Tonf, m, C','kN, mm, C')}).loads,null);});
test('PM input limits reject missing, nonfinite, fractional bar counts and bad geometry',()=>{for(const patch of [{fc:null},{B:0},{H:10000},{rebarX:2.5},{cover:30},{forces:[]},{forces:[{p:NaN,mx:0,my:0}]},{forces:[{p:'',mx:0,my:0}]}])assert.throws(()=>ctx.calculatePM({...pmInput,...patch}));});
test('client has no engineering algorithms, embedded legacy modules or remote scripts',()=>{const h=read('gas/Index.html');for(const term of ['function parseS2K','function buildModel','function calculatePMCurve','function twSectionClassify','foundation-source','eval(','<script src='])assert.ok(!h.includes(term),term);const s=read('gas/Code.gs')+read('gas/LegacyCore.gs');const publicFunctions=Object.keys(ctx).filter(n=>typeof ctx[n]==='function'&&!n.endsWith('_'));assert.deepEqual(publicFunctions,['doGet','analyzeModel','calculatePM']);assert.deepEqual(JSON.parse(read('gas/appsscript.json')).oauthScopes,[]);});

test('accept valid input beyond previous byte and row caps',()=>{
  const text='TABLE: "ANALYSIS TEST"\n'+('Value="'+ 'x'.repeat(60)+'"\n').repeat(150001);
  assert.ok(Buffer.byteLength(text)>8*1024*1024);
  const r=ctx.analyzeModel({text,name:'large synthetic'});
  assert.equal(r.tables['ANALYSIS TEST'].length,150001);
});
