// Local-only preview. Never deploy this file or the injected bridge to GAS.
const http=require('node:http'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),engine=vm.createContext({});
for(const name of ['LegacyCore.gs','Code.gs'])vm.runInContext(fs.readFileSync(path.join(root,'gas',name),'utf8'),engine);
http.createServer(async(req,res)=>{try{
 if(req.method==='POST'&&req.url==='/rpc'){let text='';for await(const c of req)text+=c;const {name,payload}=JSON.parse(text);if(!['analyzeModel','calculatePM'].includes(name))throw Error('Unknown RPC');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({result:engine[name](payload)}));return;}
 if(req.url==='/fixture'){res.setHeader('Content-Type','text/plain;charset=utf-8');res.end(fs.readFileSync(path.join(root,'工務大樓/工務大樓_20260708_e_model definition.s2k')));return;}
 let html=fs.readFileSync(path.join(root,'gas/Index.html'),'utf8');const bridge=`<script>const localBridge=(ok=()=>{},fail=()=>{})=>({withSuccessHandler(f){return localBridge(f,fail)},withFailureHandler(f){return localBridge(ok,f)},analyzeModel(payload){call('analyzeModel',payload)},calculatePM(payload){call('calculatePM',payload)}});function call(){};window.google={script:{get run(){let ok,fail;const b={withSuccessHandler(f){ok=f;return b},withFailureHandler(f){fail=f;return b}};for(const name of ['analyzeModel','calculatePM'])b[name]=payload=>fetch('/rpc',{method:'POST',body:JSON.stringify({name,payload})}).then(r=>r.json()).then(r=>{if(r.error)throw Error(r.error);ok(r.result)}).catch(fail);return b}}};</script>`;
 html=html.replace('<script>',bridge+'<script>');html=html.replace('<main>','<div style="padding:8px;background:#5d3915">本機預覽：真實本機 GS 計算，非 GAS 線上部署。<button id="previewReal">載入本機工務大樓模型</button></div><main>');html=html.replace('</body>',`<script>document.getElementById('previewReal').onclick=()=>action(async()=>importModel(await(await fetch('/fixture')).text(),'工務大樓模型（本機預覽）'));</script></body>`);res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html);
 }catch(e){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({error:e.message}));}}).listen(8001,'127.0.0.1',()=>console.log('Local preview: http://127.0.0.1:8001'));
